import api from './api'

// ==================== TYPES ====================

export type AccountType = 'ASSET' | 'LIABILITY' | 'EQUITY' | 'REVENUE' | 'EXPENSE'

export interface Account {
  id: string
  code: string
  name: string
  nameEn?: string
  type: AccountType
  category: string
  parentId?: string
  parentCode?: string
  parentName?: string
  level: number
  isActive: boolean
  isSystem: boolean
  normalBalance: 'DEBIT' | 'CREDIT'
  description?: string
  taxRelated: boolean
  balance?: {
    debit: number
    credit: number
    net: number
  }
  children?: Account[]
}

export interface JournalEntry {
  id: string
  entryNumber: string
  date: string
  referenceType?: string
  referenceId?: string
  description: string
  totalDebit: number
  totalCredit: number
  isAutoGenerated: boolean
  isPosted: boolean
  postedAt?: string
  postedBy?: string
  notes?: string
  lineCount?: number
  lines?: JournalLine[]
}

export interface JournalLine {
  id: string
  accountId: string
  accountCode?: string
  accountName?: string
  accountType?: AccountType
  lineNumber: number
  description?: string
  debit: number
  credit: number
}

export interface TrialBalanceItem {
  id: string
  code: string
  name: string
  type: AccountType
  category: string
  normalBalance: 'DEBIT' | 'CREDIT'
  openingDebit: number
  openingCredit: number
  debit: number
  credit: number
  endingDebit: number
  endingCredit: number
}

export interface TrialBalanceReport {
  startDate?: string
  endDate?: string
  accounts: TrialBalanceItem[]
  totals: {
    openingDebit: number
    openingCredit: number
    debit: number
    credit: number
    endingDebit: number
    endingCredit: number
  }
}

export interface BalanceSheetItem {
  id: string
  code: string
  name: string
  category: string
  balance: number
}

export interface BalanceSheetReport {
  asOfDate: string
  assets: {
    items: BalanceSheetItem[]
    grouped: Record<string, BalanceSheetItem[]>
    total: number
  }
  liabilities: {
    items: BalanceSheetItem[]
    grouped: Record<string, BalanceSheetItem[]>
    total: number
  }
  equity: {
    items: BalanceSheetItem[]
    grouped: Record<string, BalanceSheetItem[]>
    total: number
  }
  totalLiabilitiesAndEquity: number
  balanced: boolean
}

export interface ProfitLossItem {
  id: string
  code: string
  name: string
  category: string
  balance: number
}

export interface ProfitLossReport {
  period: {
    startDate: string
    endDate: string
  }
  revenue: {
    items: ProfitLossItem[]
    grouped: Record<string, ProfitLossItem[]>
    total: number
  }
  cogs: {
    items: ProfitLossItem[]
    total: number
  }
  grossProfit: number
  operatingExpenses: {
    items: ProfitLossItem[]
    grouped: Record<string, ProfitLossItem[]>
    total: number
  }
  operatingProfit: number
  netProfit: number
  margin: string
}

// ==================== ACCOUNTS API ====================

export const accountsApi = {
  // Initialize default chart of accounts
  init: () => api.post('/accounts/init'),
  
  // Get all accounts
  getAll: (params?: { type?: string; active?: boolean }) => 
    api.get('/accounts', { params }),
  
  // Get account by ID
  getById: (id: string) => api.get(`/accounts/${id}`),
  
  // Create account
  create: (data: Partial<Account>) => api.post('/accounts', data),
  
  // Update account
  update: (id: string, data: Partial<Account>) => api.put(`/accounts/${id}`, data),
  
  // Delete account
  delete: (id: string) => api.delete(`/accounts/${id}`),
}

// ==================== JOURNAL API ====================

export const journalApi = {
  // Get all entries
  getAll: (params?: { 
    startDate?: string; 
    endDate?: string; 
    isPosted?: boolean;
    referenceType?: string;
    accountId?: string;
  }) => api.get('/journal', { params }),
  
  // Get entry by ID
  getById: (id: string) => api.get(`/journal/${id}`),
  
  // Create entry
  create: (data: {
    date: string
    description: string
    referenceType?: string
    referenceId?: string
    notes?: string
    lines: Array<{
      accountId: string
      description?: string
      debit?: number
      credit?: number
    }>
  }) => api.post('/journal', data),
  
  // Update entry
  update: (id: string, data: Partial<JournalEntry>) => api.put(`/journal/${id}`, data),
  
  // Post entry
  post: (id: string) => api.post(`/journal/${id}/post`),
  
  // Unpost entry (admin only)
  unpost: (id: string) => api.post(`/journal/${id}/unpost`),
  
  // Delete entry
  delete: (id: string) => api.delete(`/journal/${id}`),
  
  // Auto-generate from PO
  generateFromPO: (purchaseOrderId: string, date: string) => 
    api.post('/journal/auto/purchase-order', { purchaseOrderId, date }),
  
  // Auto-generate from Sales
  generateFromSales: (orderId: string) => 
    api.post('/journal/auto/sales', { orderId }),
}

// ==================== REPORTS API ====================

export const reportsApi = {
  // Trial Balance
  getTrialBalance: (params: { startDate?: string; endDate?: string }) =>
    api.get('/reports/trial-balance', { params }),
  
  // Balance Sheet
  getBalanceSheet: (params: { asOfDate?: string }) =>
    api.get('/reports/balance-sheet', { params }),
  
  // Profit & Loss
  getProfitLoss: (params: { startDate: string; endDate: string }) =>
    api.get('/reports/profit-loss', { params }),
  
  // Cash Flow
  getCashFlow: (params: { startDate: string; endDate: string }) =>
    api.get('/reports/cash-flow', { params }),
  
  // Account Ledger
  getLedger: (accountId: string, params: { startDate?: string; endDate?: string }) =>
    api.get(`/reports/ledger/${accountId}`, { params }),
  
  // VAT Report
  getVAT: (params: { startDate?: string; endDate?: string; type?: 'input' | 'output' }) =>
    api.get('/reports/vat', { params }),
}

// ==================== CONSTANTS ====================

export const ACCOUNT_TYPES: { value: AccountType; label: string; color: string }[] = [
  { value: 'ASSET', label: 'สินทรัพย์', color: 'text-green-400' },
  { value: 'LIABILITY', label: 'หนี้สิน', color: 'text-red-400' },
  { value: 'EQUITY', label: 'ส่วนของผู้ถือหุ้น', color: 'text-purple-400' },
  { value: 'REVENUE', label: 'รายได้', color: 'text-cyan-400' },
  { value: 'EXPENSE', label: 'ค่าใช้จ่าย', color: 'text-orange-400' },
]

export const ACCOUNT_CATEGORIES: Record<AccountType, string[]> = {
  ASSET: ['CURRENT_ASSET', 'FIXED_ASSET', 'INVENTORY', 'RECEIVABLE', 'CASH', 'PREPAID', 'TAX', 'DEPOSIT'],
  LIABILITY: ['CURRENT_LIABILITY', 'LONG_TERM_LIABILITY', 'PAYABLE', 'LOAN', 'ACCRUED', 'DEFERRED', 'TAX'],
  EQUITY: ['CAPITAL', 'RESERVE', 'RETAINED_EARNINGS', 'OTHER_COMPREHENSIVE'],
  REVENUE: ['SALES', 'SERVICE', 'INTEREST', 'OTHER_REVENUE', 'CONTRA_REVENUE'],
  EXPENSE: ['COGS', 'SELLING_EXPENSE', 'ADMIN_EXPENSE', 'OTHER_EXPENSE'],
}

export default {
  accounts: accountsApi,
  journal: journalApi,
  reports: reportsApi,
}
