import { useState, useEffect, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  FileText, Plus, Search, CheckCircle, Lock, Unlock,
  Trash2, Calculator, X, ChevronDown, ChevronUp,
  Zap, ShoppingCart, ShoppingBag, RefreshCw, ArrowUpDown,
} from 'lucide-react'
import { journalApi, accountsApi, type Account } from '../../services/accounting'
import toast from 'react-hot-toast'

// ==================== Types ====================

interface RawEntry {
  id: string
  entry_number?: string
  entryNumber?: string
  date: string
  reference_type?: string
  referenceType?: string
  reference_id?: string
  description: string
  total_debit?: number
  totalDebit?: number
  total_credit?: number
  totalCredit?: number
  is_auto_generated?: number | boolean
  isAutoGenerated?: boolean
  is_posted?: number | boolean
  isPosted?: boolean
  posted_at?: string
  posted_by?: string
  notes?: string
  line_count?: number
  lineCount?: number
  lines?: RawLine[]
}

interface RawLine {
  id: string
  account_id?: string
  accountId?: string
  account_code?: string
  accountCode?: string
  account_name?: string
  accountName?: string
  account_type?: string
  accountType?: string
  line_number?: number
  lineNumber?: number
  description?: string
  debit: number
  credit: number
}

interface Entry {
  id: string
  entryNumber: string
  date: string
  referenceType?: string
  description: string
  totalDebit: number
  totalCredit: number
  isAutoGenerated: boolean
  isPosted: boolean
  postedAt?: string
  postedBy?: string
  notes?: string
  lineCount?: number
  lines?: Line[]
}

interface Line {
  id: string
  accountId: string
  accountCode?: string
  accountName?: string
  accountType?: string
  lineNumber: number
  description?: string
  debit: number
  credit: number
}

// ==================== Normalize snake_case → camelCase ====================

const normalizeLine = (l: RawLine): Line => ({
  id: l.id,
  accountId: l.account_id ?? l.accountId ?? '',
  accountCode: l.account_code ?? l.accountCode,
  accountName: l.account_name ?? l.accountName,
  accountType: l.account_type ?? l.accountType,
  lineNumber: l.line_number ?? l.lineNumber ?? 0,
  description: l.description,
  debit: l.debit ?? 0,
  credit: l.credit ?? 0,
})

const normalizeEntry = (e: RawEntry): Entry => ({
  id: e.id,
  entryNumber: e.entry_number ?? e.entryNumber ?? '',
  date: e.date,
  referenceType: e.reference_type ?? e.referenceType,
  description: e.description ?? '',
  totalDebit: e.total_debit ?? e.totalDebit ?? 0,
  totalCredit: e.total_credit ?? e.totalCredit ?? 0,
  isAutoGenerated: Boolean(e.is_auto_generated ?? e.isAutoGenerated),
  isPosted: Boolean(e.is_posted ?? e.isPosted),
  postedAt: e.posted_at,
  postedBy: e.posted_by,
  notes: e.notes,
  lineCount: e.line_count ?? e.lineCount,
  lines: e.lines?.map(normalizeLine),
})

// ==================== Helpers ====================

const fmt = (n: number) =>
  (n || 0).toLocaleString('th-TH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })

const fmtDate = (s: string) =>
  new Date(s).toLocaleDateString('th-TH', { day: 'numeric', month: 'short', year: 'numeric' })

const SOURCE_BADGE: Record<string, { label: string; color: string; icon: React.ReactNode }> = {
  POS_SALE:             { label: 'POS ขาย',    color: 'bg-cyan-500/20 text-cyan-400',    icon: <ShoppingBag className="w-3 h-3" /> },
  POS_CLEARING_TRANSFER:{ label: 'POS Clearing',color: 'bg-purple-500/20 text-purple-400',icon: <ArrowUpDown className="w-3 h-3" /> },
  PURCHASE_ORDER:       { label: 'ซื้อ',         color: 'bg-orange-500/20 text-orange-400',icon: <ShoppingCart className="w-3 h-3" /> },
  SALES_ORDER:          { label: 'ขาย',          color: 'bg-green-500/20 text-green-400',  icon: <ShoppingCart className="w-3 h-3" /> },
  MANUAL:               { label: 'Manual',       color: 'bg-gray-500/20 text-gray-400',    icon: <FileText className="w-3 h-3" /> },
}

const getSourceBadge = (refType?: string, isAuto?: boolean) => {
  if (refType && SOURCE_BADGE[refType]) return SOURCE_BADGE[refType]
  if (!isAuto) return SOURCE_BADGE.MANUAL
  return { label: 'ระบบ', color: 'bg-blue-500/20 text-blue-400', icon: <Zap className="w-3 h-3" /> }
}

// ==================== Main Component ====================

export default function JournalEntries() {
  const [entries, setEntries] = useState<Entry[]>([])
  const [accounts, setAccounts] = useState<Account[]>([])
  const [loading, setLoading] = useState(true)
  const [searchTerm, setSearchTerm] = useState('')
  const [dateRange, setDateRange] = useState({ start: '', end: '' })
  const [filterPosted, setFilterPosted] = useState<'all' | 'draft' | 'posted'>('all')
  const [showCreateModal, setShowCreateModal] = useState(false)
  const [selectedEntry, setSelectedEntry] = useState<Entry | null>(null)
  const [loadingDetail, setLoadingDetail] = useState(false)

  const fetchEntries = useCallback(async () => {
    setLoading(true)
    try {
      const params: any = {}
      if (dateRange.start) params.startDate = dateRange.start
      if (dateRange.end) params.endDate = dateRange.end
      if (filterPosted === 'draft') params.isPosted = false
      if (filterPosted === 'posted') params.isPosted = true
      const res = await journalApi.getAll(params)
      if (res.data.success) setEntries((res.data.data as RawEntry[]).map(normalizeEntry))
    } catch { toast.error('ไม่สามารถโหลดข้อมูลสมุดรายวันได้') }
    finally { setLoading(false) }
  }, [dateRange, filterPosted])

  useEffect(() => { fetchEntries() }, [fetchEntries])

  useEffect(() => {
    if (showCreateModal && accounts.length === 0) {
      accountsApi.getAll({ active: true }).then(res => {
        if (res.data.success) setAccounts(res.data.data.list.filter((a: Account) => a.level >= 2))
      })
    }
  }, [showCreateModal])

  const openDetail = async (entry: Entry) => {
    setSelectedEntry(entry)
    if (!entry.lines) {
      setLoadingDetail(true)
      try {
        const res = await journalApi.getById(entry.id)
        if (res.data.success) setSelectedEntry(normalizeEntry(res.data.data))
      } catch { toast.error('โหลดรายละเอียดไม่สำเร็จ') }
      finally { setLoadingDetail(false) }
    }
  }

  const handlePost = async (id: string, e: React.MouseEvent) => {
    e.stopPropagation()
    try {
      await journalApi.post(id)
      toast.success('ยืนยันรายการสำเร็จ')
      fetchEntries()
    } catch (err: any) { toast.error(err.response?.data?.message || 'ยืนยันไม่สำเร็จ') }
  }

  const handleDelete = async (id: string, isPosted: boolean, e: React.MouseEvent) => {
    e.stopPropagation()
    if (isPosted) { toast.error('ไม่สามารถลบรายการที่ยืนยันแล้ว'); return }
    if (!confirm('ต้องการลบรายการนี้?')) return
    try {
      await journalApi.delete(id)
      toast.success('ลบสำเร็จ')
      fetchEntries()
    } catch (err: any) { toast.error(err.response?.data?.message || 'ลบไม่สำเร็จ') }
  }

  const filtered = entries.filter(e => {
    const q = searchTerm.toLowerCase()
    return (e.entryNumber ?? '').toLowerCase().includes(q) ||
           (e.description ?? '').toLowerCase().includes(q)
  })

  const totalDebit = filtered.reduce((s, e) => s + e.totalDebit, 0)
  const totalCredit = filtered.reduce((s, e) => s + e.totalCredit, 0)
  const draftCount = filtered.filter(e => !e.isPosted).length

  return (
    <div className="space-y-5">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-2">
            <FileText className="w-7 h-7 text-cyber-primary" />
            สมุดรายวัน
          </h1>
          <p className="text-gray-400 text-sm mt-0.5">
            {filtered.length} รายการ
            {draftCount > 0 && <span className="ml-2 text-yellow-400">· {draftCount} รอดำเนินการ</span>}
          </p>
        </div>
        <div className="flex gap-2">
          <button onClick={fetchEntries} className="p-2 rounded-lg bg-cyber-card border border-cyber-border text-gray-400 hover:text-white">
            <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          </button>
          <button onClick={() => setShowCreateModal(true)}
            className="flex items-center gap-2 px-4 py-2 bg-cyber-primary text-cyber-dark font-semibold rounded-lg hover:bg-cyber-primary/80">
            <Plus className="w-4 h-4" /> บันทึกรายการ
          </button>
        </div>
      </div>

      {/* Summary Bar */}
      <div className="grid grid-cols-3 gap-3">
        <div className="bg-cyber-card border border-cyber-border rounded-xl px-4 py-3">
          <p className="text-xs text-gray-500 mb-0.5">เดบิตรวม</p>
          <p className="text-lg font-bold text-cyber-primary">฿{fmt(totalDebit)}</p>
        </div>
        <div className="bg-cyber-card border border-cyber-border rounded-xl px-4 py-3">
          <p className="text-xs text-gray-500 mb-0.5">เครดิตรวม</p>
          <p className="text-lg font-bold text-cyber-primary">฿{fmt(totalCredit)}</p>
        </div>
        <div className={`rounded-xl px-4 py-3 border ${
          Math.abs(totalDebit - totalCredit) < 0.01
            ? 'bg-cyber-green/10 border-cyber-green/30'
            : 'bg-red-500/10 border-red-500/30'
        }`}>
          <p className="text-xs text-gray-500 mb-0.5">สมดุล</p>
          <p className={`text-lg font-bold ${Math.abs(totalDebit - totalCredit) < 0.01 ? 'text-cyber-green' : 'text-red-400'}`}>
            {Math.abs(totalDebit - totalCredit) < 0.01 ? '✓ สมดุล' : `ต่าง ฿${fmt(Math.abs(totalDebit - totalCredit))}`}
          </p>
        </div>
      </div>

      {/* Filters */}
      <div className="flex flex-col sm:flex-row gap-3">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400" />
          <input type="text" placeholder="ค้นหาเลขที่ หรือคำอธิบาย..."
            value={searchTerm} onChange={e => setSearchTerm(e.target.value)}
            className="w-full pl-9 pr-3 py-2 bg-cyber-card border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary"
          />
        </div>
        <div className="flex gap-2">
          <input type="date" value={dateRange.start}
            onChange={e => setDateRange(p => ({ ...p, start: e.target.value }))}
            className="px-3 py-2 bg-cyber-card border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary"
          />
          <span className="self-center text-gray-500">–</span>
          <input type="date" value={dateRange.end}
            onChange={e => setDateRange(p => ({ ...p, end: e.target.value }))}
            className="px-3 py-2 bg-cyber-card border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary"
          />
        </div>
        <div className="flex rounded-lg overflow-hidden border border-cyber-border text-sm">
          {(['all', 'draft', 'posted'] as const).map(f => (
            <button key={f} onClick={() => setFilterPosted(f)}
              className={`px-3 py-2 transition-colors ${filterPosted === f ? 'bg-cyber-primary text-cyber-dark font-medium' : 'bg-cyber-card text-gray-400 hover:text-white'}`}>
              {f === 'all' ? 'ทั้งหมด' : f === 'draft' ? 'รอดำเนินการ' : 'ยืนยันแล้ว'}
            </button>
          ))}
        </div>
      </div>

      {/* Entries List */}
      <div className="bg-cyber-card border border-cyber-border rounded-xl overflow-hidden">
        {/* Table header */}
        <div className="hidden sm:grid grid-cols-[120px_90px_1fr_110px_110px_90px_80px] gap-3 px-4 py-2.5 bg-cyber-dark/50 border-b border-cyber-border text-xs text-gray-500 font-medium uppercase tracking-wide">
          <span>เลขที่</span>
          <span>วันที่</span>
          <span>รายการ</span>
          <span className="text-right">เดบิต</span>
          <span className="text-right">เครดิต</span>
          <span className="text-center">สถานะ</span>
          <span></span>
        </div>

        {loading ? (
          <div className="p-12 text-center">
            <div className="w-8 h-8 border-2 border-cyber-primary border-t-transparent rounded-full animate-spin mx-auto" />
          </div>
        ) : filtered.length === 0 ? (
          <div className="p-12 text-center text-gray-500">
            <FileText className="w-12 h-12 mx-auto mb-3 text-gray-700" />
            <p>ไม่พบรายการ</p>
          </div>
        ) : (
          <div className="divide-y divide-cyber-border">
            {filtered.map(entry => {
              const badge = getSourceBadge(entry.referenceType, entry.isAutoGenerated)
              return (
                <motion.div key={entry.id} initial={{ opacity: 0 }} animate={{ opacity: 1 }}
                  onClick={() => openDetail(entry)}
                  className="grid grid-cols-1 sm:grid-cols-[120px_90px_1fr_110px_110px_90px_80px] gap-3 px-4 py-3.5 hover:bg-cyber-dark/40 cursor-pointer transition-colors items-center">
                  {/* Entry number */}
                  <span className="font-mono text-sm text-cyber-primary font-semibold">
                    {entry.entryNumber || <span className="text-gray-600 italic text-xs">ไม่มีเลขที่</span>}
                  </span>
                  {/* Date */}
                  <span className="text-sm text-gray-300">{fmtDate(entry.date)}</span>
                  {/* Description + badge */}
                  <div className="min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className={`inline-flex items-center gap-1 text-xs px-1.5 py-0.5 rounded ${badge.color}`}>
                        {badge.icon}{badge.label}
                      </span>
                      {entry.isAutoGenerated && (
                        <span className="text-xs text-blue-400/60">Auto</span>
                      )}
                    </div>
                    <p className="text-sm text-white mt-0.5 truncate">{entry.description}</p>
                  </div>
                  {/* Debit */}
                  <span className="text-right text-sm font-mono text-white">
                    {entry.totalDebit > 0 ? fmt(entry.totalDebit) : <span className="text-gray-600">–</span>}
                  </span>
                  {/* Credit */}
                  <span className="text-right text-sm font-mono text-white">
                    {entry.totalCredit > 0 ? fmt(entry.totalCredit) : <span className="text-gray-600">–</span>}
                  </span>
                  {/* Status */}
                  <div className="flex justify-center">
                    {entry.isPosted ? (
                      <span className="inline-flex items-center gap-1 text-xs text-cyber-green bg-cyber-green/10 px-2 py-1 rounded-full">
                        <Lock className="w-3 h-3" /> ยืนยัน
                      </span>
                    ) : (
                      <span className="inline-flex items-center gap-1 text-xs text-yellow-400 bg-yellow-400/10 px-2 py-1 rounded-full">
                        <Unlock className="w-3 h-3" /> Draft
                      </span>
                    )}
                  </div>
                  {/* Actions */}
                  <div className="flex justify-end gap-1" onClick={e => e.stopPropagation()}>
                    {!entry.isPosted && (
                      <>
                        <button onClick={e => handlePost(entry.id, e)}
                          className="p-1.5 rounded-lg hover:bg-cyber-green/20 text-cyber-green transition-colors" title="ยืนยัน">
                          <CheckCircle className="w-4 h-4" />
                        </button>
                        <button onClick={e => handleDelete(entry.id, entry.isPosted, e)}
                          className="p-1.5 rounded-lg hover:bg-red-500/20 text-red-400 transition-colors" title="ลบ">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </>
                    )}
                  </div>
                </motion.div>
              )
            })}
          </div>
        )}
      </div>

      {/* Detail Modal */}
      <AnimatePresence>
        {selectedEntry && (
          <DetailModal
            entry={selectedEntry}
            loading={loadingDetail}
            onClose={() => setSelectedEntry(null)}
            onPost={id => { journalApi.post(id).then(() => { toast.success('ยืนยันสำเร็จ'); fetchEntries(); setSelectedEntry(null) }) }}
          />
        )}
      </AnimatePresence>

      {/* Create Modal */}
      <AnimatePresence>
        {showCreateModal && (
          <CreateModal
            accounts={accounts}
            onClose={() => setShowCreateModal(false)}
            onSuccess={() => { fetchEntries(); setShowCreateModal(false) }}
          />
        )}
      </AnimatePresence>
    </div>
  )
}

// ==================== Detail Modal ====================

function DetailModal({ entry, loading, onClose, onPost }: {
  entry: Entry
  loading: boolean
  onClose: () => void
  onPost: (id: string) => void
}) {
  const badge = getSourceBadge(entry.referenceType, entry.isAutoGenerated)
  const debitLines = entry.lines?.filter(l => l.debit > 0) ?? []
  const creditLines = entry.lines?.filter(l => l.credit > 0) ?? []

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
        className="bg-cyber-card border border-cyber-border rounded-2xl w-full max-w-2xl flex flex-col"
        style={{ maxHeight: 'calc(100vh - 2rem)' }}>
        {/* Header */}
        <div className="p-5 border-b border-cyber-border flex items-start justify-between shrink-0">
          <div>
            <div className="flex items-center gap-3 flex-wrap">
              <span className="text-lg font-bold font-mono text-cyber-primary">{entry.entryNumber}</span>
              <span className={`inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full ${badge.color}`}>
                {badge.icon}{badge.label}
              </span>
              {entry.isPosted ? (
                <span className="inline-flex items-center gap-1 text-xs text-cyber-green bg-cyber-green/10 px-2 py-0.5 rounded-full">
                  <Lock className="w-3 h-3" /> ยืนยันแล้ว
                </span>
              ) : (
                <span className="inline-flex items-center gap-1 text-xs text-yellow-400 bg-yellow-400/10 px-2 py-0.5 rounded-full">
                  <Unlock className="w-3 h-3" /> รอดำเนินการ
                </span>
              )}
            </div>
            <p className="text-gray-300 text-sm mt-1">{entry.description}</p>
            <p className="text-gray-500 text-xs mt-0.5">{fmtDate(entry.date)}</p>
          </div>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-cyber-dark text-gray-400 hover:text-white shrink-0">
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* T-Account Body */}
        <div className="overflow-y-auto p-5 space-y-4">
          {loading ? (
            <div className="p-8 text-center"><div className="w-6 h-6 border-2 border-cyber-primary border-t-transparent rounded-full animate-spin mx-auto" /></div>
          ) : (
            <>
              {/* T-Account table */}
              <div className="grid grid-cols-2 gap-3">
                {/* Debit side */}
                <div className="border border-cyber-border rounded-xl overflow-hidden">
                  <div className="px-4 py-2 bg-cyber-dark border-b border-cyber-border">
                    <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">เดบิต (Dr.)</p>
                  </div>
                  <div className="divide-y divide-cyber-border">
                    {debitLines.length === 0 ? (
                      <p className="px-4 py-3 text-xs text-gray-600">–</p>
                    ) : debitLines.map((l, i) => (
                      <div key={i} className="px-4 py-3">
                        <p className="text-sm text-white font-medium">{l.accountName}</p>
                        <p className="text-xs text-gray-500 font-mono">{l.accountCode}</p>
                        {l.description && <p className="text-xs text-gray-600 mt-0.5">{l.description}</p>}
                        <p className="text-sm font-bold text-white mt-1 text-right">฿{fmt(l.debit)}</p>
                      </div>
                    ))}
                  </div>
                  <div className="px-4 py-2 bg-cyber-dark/50 border-t border-cyber-border">
                    <p className="text-sm font-bold text-white text-right">฿{fmt(entry.totalDebit)}</p>
                  </div>
                </div>
                {/* Credit side */}
                <div className="border border-cyber-border rounded-xl overflow-hidden">
                  <div className="px-4 py-2 bg-cyber-dark border-b border-cyber-border">
                    <p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">เครดิต (Cr.)</p>
                  </div>
                  <div className="divide-y divide-cyber-border">
                    {creditLines.length === 0 ? (
                      <p className="px-4 py-3 text-xs text-gray-600">–</p>
                    ) : creditLines.map((l, i) => (
                      <div key={i} className="px-4 py-3">
                        <p className="text-sm text-white font-medium">{l.accountName}</p>
                        <p className="text-xs text-gray-500 font-mono">{l.accountCode}</p>
                        {l.description && <p className="text-xs text-gray-600 mt-0.5">{l.description}</p>}
                        <p className="text-sm font-bold text-white mt-1 text-right">฿{fmt(l.credit)}</p>
                      </div>
                    ))}
                  </div>
                  <div className="px-4 py-2 bg-cyber-dark/50 border-t border-cyber-border">
                    <p className="text-sm font-bold text-white text-right">฿{fmt(entry.totalCredit)}</p>
                  </div>
                </div>
              </div>

              {/* Balance check */}
              <div className={`flex items-center justify-between px-4 py-2.5 rounded-lg text-sm ${
                Math.abs(entry.totalDebit - entry.totalCredit) < 0.01
                  ? 'bg-cyber-green/10 border border-cyber-green/30 text-cyber-green'
                  : 'bg-red-500/10 border border-red-500/30 text-red-400'
              }`}>
                <span className="flex items-center gap-2">
                  <Calculator className="w-4 h-4" /> ตรวจสอบสมดุล
                </span>
                <span className="font-bold">
                  {Math.abs(entry.totalDebit - entry.totalCredit) < 0.01 ? '✓ สมดุล' : 'ไม่สมดุล'}
                </span>
              </div>

              {entry.notes && (
                <div className="px-4 py-3 bg-cyber-dark rounded-lg text-sm text-gray-400">
                  <span className="text-gray-600">หมายเหตุ: </span>{entry.notes}
                </div>
              )}
            </>
          )}
        </div>

        {/* Footer */}
        <div className="p-5 border-t border-cyber-border flex justify-end gap-3 shrink-0">
          <button onClick={onClose} className="px-4 py-2 text-gray-400 hover:text-white text-sm">ปิด</button>
          {!entry.isPosted && (
            <button onClick={() => onPost(entry.id)}
              className="flex items-center gap-2 px-5 py-2 bg-cyber-green/20 border border-cyber-green/40 text-cyber-green font-medium rounded-lg hover:bg-cyber-green/30 text-sm">
              <CheckCircle className="w-4 h-4" /> ยืนยันรายการ
            </button>
          )}
        </div>
      </motion.div>
    </div>
  )
}

// ==================== Create Modal ====================

function CreateModal({ accounts, onClose, onSuccess }: {
  accounts: Account[]
  onClose: () => void
  onSuccess: () => void
}) {
  const today = new Date()
  const todayStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`
  const [date, setDate] = useState(todayStr)
  const [description, setDescription] = useState('')
  const [notes, setNotes] = useState('')
  const [lines, setLines] = useState([
    { accountId: '', description: '', debit: '', credit: '', side: 'debit' as 'debit' | 'credit' },
    { accountId: '', description: '', debit: '', credit: '', side: 'credit' as 'debit' | 'credit' },
  ])
  const [saving, setSaving] = useState(false)

  const totalDebit = lines.reduce((s, l) => s + (parseFloat(l.debit) || 0), 0)
  const totalCredit = lines.reduce((s, l) => s + (parseFloat(l.credit) || 0), 0)
  const balanced = Math.abs(totalDebit - totalCredit) < 0.01

  const updateLine = (i: number, field: string, value: string) => {
    setLines(prev => prev.map((l, idx) => idx === i ? { ...l, [field]: value } : l))
  }

  const addLine = (side: 'debit' | 'credit') => {
    setLines(prev => [...prev, { accountId: '', description: '', debit: '', credit: '', side }])
  }

  const removeLine = (i: number) => {
    if (lines.length <= 2) { toast.error('ต้องมีอย่างน้อย 2 รายการ'); return }
    setLines(prev => prev.filter((_, idx) => idx !== i))
  }

  const handleSubmit = async () => {
    if (!description) { toast.error('กรุณากรอกคำอธิบาย'); return }
    if (!balanced) { toast.error('ยอดเดบิต-เครดิตไม่สมดุล'); return }
    const validLines = lines.filter(l => l.accountId && (parseFloat(l.debit) > 0 || parseFloat(l.credit) > 0))
    if (validLines.length < 2) { toast.error('ต้องมีอย่างน้อย 2 บรรทัดที่มีข้อมูล'); return }
    setSaving(true)
    try {
      const res = await journalApi.create({
        date, description, notes,
        lines: validLines.map(l => ({
          accountId: l.accountId,
          description: l.description || undefined,
          debit: parseFloat(l.debit) || 0,
          credit: parseFloat(l.credit) || 0,
        }))
      })
      if (res.data.success) { toast.success('บันทึกรายการสำเร็จ'); onSuccess() }
    } catch (err: any) { toast.error(err.response?.data?.message || 'บันทึกไม่สำเร็จ') }
    finally { setSaving(false) }
  }

  const debitLines = lines.map((l, i) => ({ ...l, i })).filter(l => l.side === 'debit')
  const creditLines = lines.map((l, i) => ({ ...l, i })).filter(l => l.side === 'credit')

  const LineRow = ({ l, i }: { l: typeof lines[0] & { i: number }; i: number }) => (
    <div className="space-y-2 p-3 bg-cyber-dark rounded-lg relative">
      <button onClick={() => removeLine(l.i)} className="absolute top-2 right-2 p-1 text-gray-600 hover:text-red-400">
        <X className="w-3.5 h-3.5" />
      </button>
      <select value={l.accountId} onChange={e => updateLine(l.i, 'accountId', e.target.value)}
        className="w-full px-3 py-2 bg-cyber-card border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary">
        <option value="">{accounts.length === 0 ? 'กำลังโหลด...' : '— เลือกบัญชี —'}</option>
        {['ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE'].map(type => {
          const group = accounts.filter(a => a.type === type)
          if (!group.length) return null
          const label = { ASSET: 'สินทรัพย์', LIABILITY: 'หนี้สิน', EQUITY: 'ทุน', REVENUE: 'รายได้', EXPENSE: 'ค่าใช้จ่าย' }[type]!
          return (
            <optgroup key={type} label={label}>
              {group.map(a => <option key={a.id} value={a.id}>{a.code} – {a.name}</option>)}
            </optgroup>
          )
        })}
      </select>
      <div className="grid grid-cols-2 gap-2">
        <input placeholder="คำอธิบาย (optional)" value={l.description}
          onChange={e => updateLine(l.i, 'description', e.target.value)}
          className="px-3 py-2 bg-cyber-card border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary col-span-2" />
        <div className="relative">
          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-gray-500">Dr.</span>
          <input type="number" placeholder="0" value={l.debit}
            onChange={e => updateLine(l.i, 'debit', e.target.value)}
            onFocus={e => e.target.select()}
            className="w-full pl-9 pr-3 py-2 bg-cyber-card border border-cyber-border rounded-lg text-white text-sm font-mono focus:outline-none focus:border-yellow-400" />
        </div>
        <div className="relative">
          <span className="absolute left-3 top-1/2 -translate-y-1/2 text-xs text-gray-500">Cr.</span>
          <input type="number" placeholder="0" value={l.credit}
            onChange={e => updateLine(l.i, 'credit', e.target.value)}
            onFocus={e => e.target.select()}
            className="w-full pl-9 pr-3 py-2 bg-cyber-card border border-cyber-border rounded-lg text-white text-sm font-mono focus:outline-none focus:border-blue-400" />
        </div>
      </div>
    </div>
  )

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <motion.div initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
        className="bg-cyber-card border border-cyber-border rounded-2xl w-full max-w-2xl flex flex-col"
        style={{ maxHeight: 'calc(100vh - 2rem)' }}>
        <div className="p-5 border-b border-cyber-border flex items-center justify-between shrink-0">
          <h2 className="text-lg font-bold text-white flex items-center gap-2">
            <FileText className="w-5 h-5 text-cyber-primary" /> บันทึกรายการคู่
          </h2>
          <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-cyber-dark text-gray-400 hover:text-white"><X className="w-5 h-5" /></button>
        </div>

        <div className="overflow-y-auto p-5 space-y-4">
          {/* Meta */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs text-gray-400 mb-1.5">วันที่</label>
              <input type="date" value={date} onChange={e => setDate(e.target.value)}
                className="w-full px-3 py-2 bg-cyber-dark border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary" />
            </div>
            <div>
              <label className="block text-xs text-gray-400 mb-1.5">คำอธิบาย *</label>
              <input type="text" value={description} onChange={e => setDescription(e.target.value)}
                placeholder="เช่น บันทึกรับชำระ, บันทึกค่าใช้จ่าย..."
                className="w-full px-3 py-2 bg-cyber-dark border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary" />
            </div>
          </div>

          {/* T-Account Layout */}
          <div className="grid grid-cols-2 gap-4">
            {/* Debit */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-semibold text-yellow-400 uppercase tracking-wide">เดบิต (Dr.)</span>
                <span className="text-xs font-mono text-yellow-400">฿{fmt(totalDebit)}</span>
              </div>
              <div className="space-y-2">
                {debitLines.map((l) => <LineRow key={l.i} l={l} i={l.i} />)}
                <button onClick={() => addLine('debit')}
                  className="w-full py-2 border border-dashed border-yellow-500/30 text-yellow-400/60 hover:text-yellow-400 hover:border-yellow-500/60 rounded-lg text-xs transition-colors">
                  + เพิ่มบรรทัดเดบิต
                </button>
              </div>
            </div>
            {/* Credit */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-semibold text-blue-400 uppercase tracking-wide">เครดิต (Cr.)</span>
                <span className="text-xs font-mono text-blue-400">฿{fmt(totalCredit)}</span>
              </div>
              <div className="space-y-2">
                {creditLines.map((l) => <LineRow key={l.i} l={l} i={l.i} />)}
                <button onClick={() => addLine('credit')}
                  className="w-full py-2 border border-dashed border-blue-500/30 text-blue-400/60 hover:text-blue-400 hover:border-blue-500/60 rounded-lg text-xs transition-colors">
                  + เพิ่มบรรทัดเครดิต
                </button>
              </div>
            </div>
          </div>

          {/* Balance Check */}
          <div className={`flex items-center justify-between px-4 py-2.5 rounded-lg text-sm ${
            balanced ? 'bg-cyber-green/10 border border-cyber-green/30' : 'bg-red-500/10 border border-red-500/30'
          }`}>
            <span className={`flex items-center gap-2 ${balanced ? 'text-cyber-green' : 'text-red-400'}`}>
              <Calculator className="w-4 h-4" />
              {balanced ? '✓ สมดุล — พร้อมบันทึก' : `ไม่สมดุล: ต่างกัน ฿${fmt(Math.abs(totalDebit - totalCredit))}`}
            </span>
            <span className="text-xs text-gray-500">Dr. {fmt(totalDebit)} / Cr. {fmt(totalCredit)}</span>
          </div>

          <div>
            <label className="block text-xs text-gray-400 mb-1.5">หมายเหตุ (optional)</label>
            <textarea value={notes} onChange={e => setNotes(e.target.value)} rows={2}
              className="w-full px-3 py-2 bg-cyber-dark border border-cyber-border rounded-lg text-white text-sm focus:outline-none focus:border-cyber-primary resize-none" />
          </div>
        </div>

        <div className="p-5 border-t border-cyber-border flex justify-end gap-3 shrink-0">
          <button onClick={onClose} className="px-4 py-2 text-gray-400 hover:text-white text-sm">ยกเลิก</button>
          <button onClick={handleSubmit} disabled={saving || !balanced}
            className="flex items-center gap-2 px-6 py-2.5 bg-cyber-primary text-cyber-dark font-semibold rounded-lg hover:bg-cyber-primary/80 disabled:opacity-40 disabled:cursor-not-allowed text-sm">
            {saving ? <div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" /> : <CheckCircle className="w-4 h-4" />}
            บันทึกรายการ
          </button>
        </div>
      </motion.div>
    </div>
  )
}
