// Mock Database for Development/Testing

export const users = [
  {
    id: '1',
    email: 'admin@example.com',
    password: 'admin123',
    name: 'Admin User',
    role: 'ADMIN',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

export const customers = [
  {
    id: '1',
    code: 'CUS-001',
    name: 'Hotel Grand Deluxe',
    type: 'HOTEL',
    contactName: 'John Smith',
    email: 'john@hotelgrand.com',
    phone: '+66 2-345-6789',
    address: '123 Sukhumvit Road',
    city: 'Bangkok',
    creditLimit: 500000,
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'CUS-002',
    name: 'ABC Trading Co.',
    type: 'WHOLESALE',
    contactName: 'Sarah Johnson',
    email: 'sarah@abctrading.com',
    phone: '+66 2-456-7890',
    address: '456 Chang Klan Road',
    city: 'Chiang Mai',
    creditLimit: 300000,
    status: 'ACTIVE',
    createdAt: new Date('2024-01-02'),
    updatedAt: new Date('2024-01-02'),
  },
  {
    id: '3',
    code: 'CUS-003',
    name: 'Resort Paradise',
    type: 'HOTEL',
    contactName: 'Mike Wilson',
    email: 'mike@resortparadise.com',
    phone: '+66 76-234-567',
    address: '789 Beach Road',
    city: 'Phuket',
    creditLimit: 400000,
    status: 'ACTIVE',
    createdAt: new Date('2024-01-03'),
    updatedAt: new Date('2024-01-03'),
  },
  {
    id: '4',
    code: 'CUS-004',
    name: 'Sleep Well Store',
    type: 'RETAIL',
    contactName: 'Emma Davis',
    email: 'emma@sleepwell.com',
    phone: '+66 2-567-8901',
    address: '321 Ratchadaphisek Road',
    city: 'Bangkok',
    creditLimit: 150000,
    status: 'ACTIVE',
    createdAt: new Date('2024-01-04'),
    updatedAt: new Date('2024-01-04'),
  },
]

export const products = [
  {
    id: '1',
    code: 'PROD-001',
    name: 'King Size Mattress Premium',
    category: 'Mattress',
    description: 'Premium king size mattress with spring coils',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'PROD-002',
    name: 'Queen Size Mattress',
    category: 'Mattress',
    description: 'Standard queen size mattress',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'PROD-003',
    name: 'Premium Pillow Set',
    category: 'Pillow',
    description: 'Memory foam pillow set (2 pieces)',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'PROD-004',
    name: 'Luxury Blanket',
    category: 'Blanket',
    description: 'Soft fleece blanket',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

export const materials = [
  {
    id: '1',
    code: 'MAT-001',
    name: 'Foam Layer',
    unit: 'kg',
    unitCost: 600,
    minStock: 500,
    maxStock: 2000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    code: 'MAT-002',
    name: 'Spring Coils',
    unit: 'units',
    unitCost: 5,
    minStock: 2000,
    maxStock: 8000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    code: 'MAT-003',
    name: 'Fabric Cover',
    unit: 'meters',
    unitCost: 250,
    minStock: 100,
    maxStock: 500,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    code: 'MAT-004',
    name: 'Thread',
    unit: 'roll',
    unitCost: 200,
    minStock: 50,
    maxStock: 200,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    code: 'MAT-005',
    name: 'Zipper',
    unit: 'unit',
    unitCost: 50,
    minStock: 500,
    maxStock: 2000,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
]

export const boms = [
  {
    id: '1',
    productId: '1',
    version: 'v2.1',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    materials: [
      { materialId: '1', quantity: 2.5, unit: 'kg' },
      { materialId: '2', quantity: 800, unit: 'units' },
      { materialId: '3', quantity: 3.5, unit: 'meters' },
      { materialId: '4', quantity: 1, unit: 'roll' },
      { materialId: '5', quantity: 1, unit: 'unit' },
    ],
  },
  {
    id: '2',
    productId: '3',
    version: 'v1.5',
    status: 'ACTIVE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
    materials: [
      { materialId: '1', quantity: 0.5, unit: 'kg' },
      { materialId: '3', quantity: 0.8, unit: 'meters' },
      { materialId: '4', quantity: 0.5, unit: 'roll' },
    ],
  },
]

export const stockItems = [
  {
    id: '1',
    sku: 'RM-FOAM-001',
    name: 'Foam Material',
    category: 'RAW_MATERIAL',
    materialId: '1',
    productId: null,
    quantity: 150,
    unit: 'kg',
    minStock: 500,
    maxStock: 2000,
    location: 'Warehouse A - Zone 1',
    status: 'CRITICAL',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    sku: 'RM-SPRING-002',
    name: 'Spring Coils',
    category: 'RAW_MATERIAL',
    materialId: '2',
    productId: null,
    quantity: 5400,
    unit: 'units',
    minStock: 2000,
    maxStock: 8000,
    location: 'Warehouse A - Zone 2',
    status: 'ADEQUATE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    sku: 'FG-MATT-K-PREM',
    name: 'King Mattress Premium',
    category: 'FINISHED_GOODS',
    materialId: null,
    productId: '1',
    quantity: 180,
    unit: 'units',
    minStock: 50,
    maxStock: 200,
    location: 'Warehouse C - Zone 1',
    status: 'ADEQUATE',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '4',
    sku: 'FG-PILL-PREM',
    name: 'Premium Pillow',
    category: 'FINISHED_GOODS',
    materialId: null,
    productId: '3',
    quantity: 850,
    unit: 'units',
    minStock: 200,
    maxStock: 600,
    location: 'Warehouse C - Zone 2',
    status: 'OVERSTOCK',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '5',
    sku: 'RM-FABRIC-003',
    name: 'Fabric Cover',
    category: 'RAW_MATERIAL',
    materialId: '3',
    productId: null,
    quantity: 80,
    unit: 'meters',
    minStock: 100,
    maxStock: 500,
    location: 'Warehouse A - Zone 3',
    status: 'LOW',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-15'),
  },
]

export const orders = [
  {
    id: '1',
    orderNumber: 'ORD-1234',
    customerId: '1',
    orderDate: new Date('2024-01-15'),
    deliveryDate: new Date('2024-02-01'),
    totalAmount: 125000,
    status: 'PROCESSING',
    notes: 'Urgent order for hotel renovation',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    items: [
      {
        productId: '1',
        quantity: 50,
        unitPrice: 2500,
        totalPrice: 125000,
      },
    ],
  },
  {
    id: '2',
    orderNumber: 'ORD-1233',
    customerId: '2',
    orderDate: new Date('2024-01-14'),
    deliveryDate: new Date('2024-01-28'),
    totalAmount: 80000,
    status: 'COMPLETED',
    notes: '',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    items: [
      {
        productId: '3',
        quantity: 200,
        unitPrice: 400,
        totalPrice: 80000,
      },
    ],
  },
  {
    id: '3',
    orderNumber: 'ORD-1232',
    customerId: '3',
    orderDate: new Date('2024-01-14'),
    deliveryDate: null,
    totalAmount: 60000,
    status: 'PENDING',
    notes: '',
    createdAt: new Date('2024-01-14'),
    updatedAt: new Date('2024-01-14'),
    items: [
      {
        productId: '2',
        quantity: 30,
        unitPrice: 2000,
        totalPrice: 60000,
      },
    ],
  },
  {
    id: '4',
    orderNumber: 'ORD-1231',
    customerId: '4',
    orderDate: new Date('2024-01-13'),
    deliveryDate: new Date('2024-01-27'),
    totalAmount: 35000,
    status: 'COMPLETED',
    notes: '',
    createdAt: new Date('2024-01-13'),
    updatedAt: new Date('2024-01-13'),
    items: [
      {
        productId: '4',
        quantity: 100,
        unitPrice: 350,
        totalPrice: 35000,
      },
    ],
  },
]
